In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as plx

In [2]:
books_data = pd.read_csv(r"C:\Users\Sukh-e\Desktop\Classes\Data Science class\NumPY\Python 10\ML\Books_data.csv")

In [3]:
books_data.head()

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",...,01/28/13,[],2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",...,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,2.1

In [4]:
books_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52478 entries, 0 to 52477
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bookId            52478 non-null  object
 1   title             52478 non-null  object
 2   series            23470 non-null  object
 3   author            52478 non-null  object
 4   rating            52478 non-null  float64
 5   description       51140 non-null  object
 6   language          48672 non-null  object
 7   isbn              52478 non-null  object
 8   genres            52478 non-null  object
 9   characters        52478 non-null  object
 10  bookFormat        51005 non-null  object
 11  edition           4955 non-null   object
 12  pages             50131 non-null  object
 13  publisher         48782 non-null  object
 14  publishDate       51598 non-null  object
 15  firstPublishDate  31152 non-null  object
 16  awards            52478 non-null  object
 17  numRatings        52478 non-null  int64
 18  ratingsByStars    52478 non-null  object
 19  likedPercent      51856 non-null  float64
 20  setting           52478 non-null  object
 21  coverImg          51873 non-null  object
 22  bbeScore          52478 non-null  int64
 23  bbeVotes          52478 non-null  int64
 24  price             38113 non-null  object
dtypes: float64(2), int64(3), object(20)
memory usage: 10.0+ MB

In [5]:
books_data.isnull().sum()

bookId                  0
title                   0
series              29008
author                  0
rating                  0
description          1338
language             3806
isbn                    0
genres                  0
characters              0
bookFormat           1473
edition             47523
pages                2347
publisher            3696
publishDate           880
firstPublishDate    21326
awards                  0
numRatings              0
ratingsByStars          0
likedPercent          622
setting                 0
coverImg              605
bbeScore                0
bbeVotes                0
price               14365
dtype: int64

In [6]:
books_data.columns

Index(['bookId', 'title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

In [7]:
books_data = books_data[['title','author','description','language','genres','pages','awards','likedPercent']]

In [8]:
books_data.head()

,title,author,description,language,genres,pages,awards,likedPercent
0,The Hunger Games,Suzanne Collins,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,['Locus Award Nominee for Best Young Adult Boo...,96.0
1,Harry Potter and the Order of the Phoenix,"J.K. Rowling, Mary GrandPré (Illustrator)",There is a door at the end of a silent corrido...,English,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,['Bram Stoker Award for Works for Young Reader...,98.0
2,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,English,"['Classics', 'Fiction', 'Historical Fiction', ...",324,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",95.0
3,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",Alternate cover edition of ISBN 9780679783268S...,English,"['Classics', 'Fiction', 'Romance', 'Historical...",279,[],94.0
4,Twilight,Stephenie Meyer,About three things I was absolutely positive.\...,English,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,"['Georgia Peach Book Award (2007)', 'Buxtehude...",78.0

In [9]:
books_data.dropna(inplace=True)
books_data.reset_index(drop=True,inplace=True)

In [10]:
books_data.isnull().sum()

title           0
author          0
description     0
language        0
genres          0
pages           0
awards          0
likedPercent    0
dtype: int64

In [11]:
books_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45895 entries, 0 to 45894
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         45895 non-null  object
 1   author        45895 non-null  object
 2   description   45895 non-null  object
 3   language      45895 non-null  object
 4   genres        45895 non-null  object
 5   pages         45895 non-null  object
 6   awards        45895 non-null  object
 7   likedPercent  45895 non-null  float64
dtypes: float64(1), object(7)
memory usage: 2.8+ MB

In [12]:
def set_author(authors):
    temp = []
    authors = authors.split(',')
    count = 1
    for author in authors:
        temp.append(author.replace(' ',''))
        if count==2:
            break
        count+=1
    return temp

In [13]:
set_author('Charlotte Brontë, Michael Mason (Editor), Barnett Freedman (Illustrator)')

['CharlotteBrontë', 'MichaelMason(Editor)']

In [14]:
books_data['author'][18]

'Charlotte Brontë, Michael Mason (Editor), Barnett Freedman (Illustrator)'

In [15]:
books_data['author'] = books_data['author'].apply(set_author)

In [16]:
def set_description(description):
        description = description.replace('.','')
        description = description.replace(',','')
        description = description.replace('--','')
        return description.lower().split()

In [17]:
books_data['description'] = books_data['description'].apply(set_description)

In [18]:
books_data['description'][0]

['winning',
 'means',
 'fame',
 'and',
 'fortunelosing',
 'means',
 'certain',
 'deaththe',
 'hunger',
 'games',
 'have',
 'begun',
 'in',
 'the',
 'ruins',
 'of',
 'a',
 'place',
 'once',
 'known',
 'as',
 'north',
 'america',
 'lies',
 'the',
 'nation',
 'of',
 'panem',
 'a',
 'shining',
 'capitol',
 'surrounded',
 'by',
 'twelve',
 'outlying',
 'districts',
 'the',
 'capitol',
 'is',
 'harsh',
 'and',
 'cruel',
 'and',
 'keeps',
 'the',
 'districts',
 'in',
 'line',
 'by',
 'forcing',
 'them',
 'all',
 'to',
 'send',
 'one',
 'boy',
 'and',
 'once',
 'girl',
 'between',
 'the',
 'ages',
 'of',
 'twelve',
 'and',
 'eighteen',
 'to',
 'participate',
 'in',
 'the',
 'annual',
 'hunger',
 'games',
 'a',
 'fight',
 'to',
 'the',
 'death',
 'on',
 'live',
 'tvsixteen-year-old',
 'katniss',
 'everdeen',
 'regards',
 'it',
 'as',
 'a',
 'death',
 'sentence',
 'when',
 'she',
 'steps',
 'forward',
 'to',
 'take',
 'her',
 "sister's",
 'place',
 'in',
 'the',
 'games',
 'but',
 'katniss',
 'has',
 'been',
 'close',
 'to',
 'dead',
 'before—and',
 'survival',
 'for',
 'her',
 'is',
 'second',
 'nature',
 'without',
 'really',
 'meaning',
 'to',
 'she',
 'becomes',
 'a',
 'contender',
 'but',
 'if',
 'she',
 'is',
 'to',
 'win',
 'she',
 'will',
 'have',
 'to',
 'start',
 'making',
 'choices',
 'that',
 'weight',
 'survival',
 'against',
 'humanity',
 'and',
 'life',
 'against',
 'love']

In [19]:
def set_language(lang):
    lang = lang.replace(' ','')
    if ';' in lang:
        if ',' in lang:
            temp = lang.split(',')
            return [temp[0]]+temp[1].split(';')
        else:
            return lang.split(';')
    else:
        return [lang]

In [20]:
['Bokmål','Norwegian;NorwegianBokmål']

['Bokmål', 'Norwegian;NorwegianBokmål']

In [21]:
for i in books_data['language'].apply(set_language):
    if len(i)>1:
        print(i)

['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Panjabi', 'Punjabi']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Catalan', 'Valencian']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Filipino', 'Pilipino']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Bokmål', 'Norwegian', 'NorwegianBokmål']
['Bokmål', 'Norwegian', 'NorwegianBokmål']

In [22]:
books_data['language'] = books_data['language'].apply(set_language)

In [23]:
def set_genres(genres):
    genres = eval(genres)
    temp = []
    for genre in genres:
        temp.append(genre.replace(' ',''))
    return temp

In [24]:
books_data['genres'] = books_data['genres'].apply(set_genres)

In [25]:
def set_awards(awards):
    awards = eval(awards)
    temp = []
    for award in awards:
        temp.append(award.replace(' ',''))
    return temp

In [26]:
books_data['awards'] = books_data['awards'].apply(set_awards)

In [27]:
def set_pages(pages):
    try:
        return [eval(pages)]
    except:
        return [1]

In [28]:
books_data['pages'] = books_data['pages'].apply(set_pages)

In [29]:
books_data['likedPercent'] = books_data['likedPercent'].apply(lambda liked : [liked])

In [30]:
books_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45895 entries, 0 to 45894
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         45895 non-null  object
 1   author        45895 non-null  object
 2   description   45895 non-null  object
 3   language      45895 non-null  object
 4   genres        45895 non-null  object
 5   pages         45895 non-null  object
 6   awards        45895 non-null  object
 7   likedPercent  45895 non-null  object
dtypes: object(8)
memory usage: 2.8+ MB

In [31]:
books_data.head()

,title,author,description,language,genres,pages,awards,likedPercent
0,The Hunger Games,[SuzanneCollins],"[winning, means, fame, and, fortunelosing, mea...",[English],"[YoungAdult, Fiction, Dystopia, Fantasy, Scien...",[374],"[LocusAwardNomineeforBestYoungAdultBook(2009),...",[96.0]
1,Harry Potter and the Order of the Phoenix,"[J.K.Rowling, MaryGrandPré(Illustrator)]","[there, is, a, door, at, the, end, of, a, sile...",[English],"[Fantasy, YoungAdult, Fiction, Magic, Children...",[870],"[BramStokerAwardforWorksforYoungReaders(2003),...",[98.0]
2,To Kill a Mockingbird,[HarperLee],"[the, unforgettable, novel, of, a, childhood, ...",[English],"[Classics, Fiction, HistoricalFiction, School,...",[324],"[PulitzerPrizeforFiction(1961), AudieAwardforC...",[95.0]
3,Pride and Prejudice,"[JaneAusten, AnnaQuindlen(Introduction)]","[alternate, cover, edition, of, isbn, 97806797...",[English],"[Classics, Fiction, Romance, HistoricalFiction...",[279],[],[94.0]
4,Twilight,[StephenieMeyer],"[about, three, things, i, was, absolutely, pos...",[English],"[YoungAdult, Fantasy, Romance, Vampires, Ficti...",[501],"[GeorgiaPeachBookAward(2007), BuxtehuderBulle(...",[78.0]

In [32]:
books_data['Tag'] = books_data['author'] + books_data['description'] + books_data['language'] + books_data['genres'] + books_data['pages'] + books_data['awards'] + books_data['likedPercent']

In [33]:
books = books_data[['title','Tag']]

In [34]:
books.head()

,title,Tag
0,The Hunger Games,"[SuzanneCollins, winning, means, fame, and, fo..."
1,Harry Potter and the Order of the Phoenix,"[J.K.Rowling, MaryGrandPré(Illustrator), there..."
2,To Kill a Mockingbird,"[HarperLee, the, unforgettable, novel, of, a, ..."
3,Pride and Prejudice,"[JaneAusten, AnnaQuindlen(Introduction), alter..."
4,Twilight,"[StephenieMeyer, about, three, things, i, was,..."

In [35]:
# love
# loving 
# loved

In [36]:
from nltk.stem import PorterStemmer

porter_stemmer = PorterStemmer()

In [37]:
porter_stemmer.stem('PLAY')

'play'

In [38]:
def stem_words(tag):
    temp = []
    for word in tag:
        word = porter_stemmer.stem(str(word))
        temp.append(word)
    return temp

In [39]:
books['Tag'] = books['Tag'].apply(stem_words)

C:\Users\Sukh-e\AppData\Local\Temp\ipykernel_11352\4016483297.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Tag'] = books['Tag'].apply(stem_words)

In [40]:
books['Tag'] = books['Tag'].apply(lambda tag: ' '.join(tag))

C:\Users\Sukh-e\AppData\Local\Temp\ipykernel_11352\754635690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  books['Tag'] = books['Tag'].apply(lambda tag: ' '.join(tag))

In [41]:
books.head()

,title,Tag
0,The Hunger Games,suzannecollin win mean fame and fortunelos mea...
1,Harry Potter and the Order of the Phoenix,j.k.rowl marygrandpré(illustrator) there is a ...
2,To Kill a Mockingbird,harperle the unforgett novel of a childhood in...
3,Pride and Prejudice,janeausten annaquindlen(introduction) altern c...
4,Twilight,stepheniemey about three thing i wa absolut po...

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=2500)

In [43]:
tfidf.fit(books['Tag'])

TfidfVectorizer(max_features=2500)

In [44]:
books_vectors = tfidf.transform(books['Tag']).toarray()

In [45]:
books_vectors.shape

(45895, 2500)

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

similar_books = cosine_similarity(books_vectors)

In [52]:
similar_books[0]

array([1.        , 0.05629494, 0.08294442, ..., 0.11774316, 0.0627045 ,
       0.07618783])

In [61]:
# Example :
lst = [34,64,12,78]
lst = list(enumerate(lst))
sorted(lst,reverse=True,key=lambda x:x[1])

[(3, 78), (1, 64), (0, 34), (2, 12)]

In [51]:
sorted(similar_books[0],reverse=True)

[1.0000000000000004,
 0.7128851416268434,
 0.6749220299322469,
 0.6337535101231002,
 0.6143345960750873,
 0.6124576142701745,
 0.5762164894709846,
 0.5760746145205728,
 0.571542266477009,
 0.5682092117390377,
 0.5529711820971454,
 0.5417257137588345,
 0.5160523409349413,
 0.5159256585670816,
 0.5051693044157685,
 0.5014989192420019,
 0.4913220244064306,
 0.4853831549608462,
 0.4658977913162985,
 0.45782719585951936,
 0.45531198952306484,
 0.4543424216528668,
 0.4524989491103261,
 0.45232970833572816,
 0.4488764514765865,
 0.44231754493356645,
 0.44032286093616674,
 0.43970230270343297,
 0.4364570962162799,
 0.4362506020758661,
 0.4358067300151422,
 0.43280973869171624,
 0.42593902378273757,
 0.4248352501363956,
 0.41971682920000963,
 0.4143669574386859,
 0.41236395211869764,
 0.4118709681508186,
 0.4107070748709686,
 0.40808552243140694,
 0.40719513648682926,
 0.4071547338280072,
 0.4069143059441362,
 0.4050286908821761,
 0.40466199834033556,
 0.4040216422337616,
 0.400012934640251,
 0.39947985988801793,
 0.39874135135807126,
 0.39503846372120677,
 0.3922159628312925,
 0.3916476131341722,
 0.38974782468310426,
 0.38253211609921844,
 0.3791156856299478,
 0.3761202693084267,
 0.37519531994022043,
 0.3713359470473888,
 0.369588621652926,
 0.3663005016127262,
 0.36544398715696935,
 0.36458158571411575,
 0.3635448178990419,
 0.3626775660338746,
 0.3578107253027015,
 0.3572059082257295,
 0.35693155861491144,
 0.3563609575436378,
 0.3558006749363065,
 0.35539128950979115,
 0.3553413007286702,
 0.3552468342343959,
 0.35426178372708544,
 0.3519030741881698,
 0.34919184172938994,
 0.34725982726396404,
 0.34724835245262264,
 0.34403738409801704,
 0.34385199234609615,
 0.3399277337246064,
 0.3397066626450123,
 0.3394926555727409,
 0.33618366177021414,
 0.3353228427105648,
 0.3335246491824405,
 0.3333736562426201,
 0.33333479573941355,
 0.3322339438496185,
 0.33176305124879224,
 0.32797355202560746,
 0.3247409275584056,
 0.3222055198307858,
 0.32189129644447856,
 0.321354925463533,
 0.3191003106978573,
 0.3177027588919831,
 0.31712696152099173,
 0.31700935210620496,
 0.3148541716722515,
 0.3147499376054879,
 0.3132229517580663,
 0.310472097503632,
 0.3099341983406101,
 0.30856044811318784,
 0.3085273484316916,
 0.30837515799032916,
 0.30701638365256584,
 0.30662361459160165,
 0.3054652604951944,
 0.30495363907419076,
 0.3047665658160767,
 0.3030773716056862,
 0.30266240010259154,
 0.30262072974864046,
 0.3024982455569655,
 0.3008581465469251,
 0.30036984811910283,
 0.30024582785792403,
 0.29933219388383353,
 0.2990476898120958,
 0.2981176513384,
 0.29764668852826814,
 0.29739986796851803,
 0.2963887204661443,
 0.2958643239852018,
 0.2953867593903326,
 0.2951191159603083,
 0.29504928586679763,
 0.294343442842828,
 0.29429202921413045,
 0.2942697941031346,
 0.29399659900336705,
 0.29392658036108654,
 0.29379360185052406,
 0.2933009467884512,
 0.29252339240414404,
 0.2917150642551234,
 0.29160820119517433,
 0.2916006976627201,
 0.2903881022672804,
 0.28986457547197253,
 0.2884962698895087,
 0.28678963205240354,
 0.285710078209034,
 0.28513579821584056,
 0.28474945843584637,
 0.2847374086755586,
 0.28455133845286695,
 0.2845114018703819,
 0.2838064169198199,
 0.28247264903745795,
 0.28214504354886055,
 0.28129386329315564,
 0.2806395940714484,
 0.2804880852931927,
 0.2798360637032082,
 0.2789473045783036,
 0.278372573612881,
 0.27830737644089487,
 0.27820436217603706,
 0.2775123096941753,
 0.277006044874209,
 0.2769719995017523,
 0.276774747787207,
 0.2767621098480091,
 0.2765227531944267,
 0.27641707847753993,
 0.2753016098750427,
 0.27523230567887413,
 0.27480223440711254,
 0.2747434905704779,
 0.2736854401588485,
 0.27296150440041,
 0.27252990380964326,
 0.27209852627820214,
 0.2709838393429105,
 0.26978367884799037,
 0.2692693746251501,
 0.2690274746335859,
 0.2689451010565205,
 0.2686642724939179,
 0.26865553557317373,
 0.26848859136861525,
 0.2664326415928231,
 0.2655648992933432,
 0.26545766504412044,
 0.2629027166562689,
 0.26248031137027034,
 0.2620024598912858,
 0.26167061693902244,
 0.2611589920686334,
 0.2602671800645076,
 0.25969768529086806,
 0.25946833540633063,
 0.2591153019680897,
 0.2585033027707476,
 0.25844764952803617,
 0.2577060317710126,
 0.25748610659844445,
 0.25734447977853264,
 0.2567043839390866,
 0.2566346677379128,
 0.255301162965434,
 0.2550695409909935,
 0.25471827874393516,
 0.2536023304140966,
 0.25335426048836523,
 0.25259554736577433,
 0.2514534017350382,
 0.2513648833427967,
 0.25051157084844383,
 0.2503074785157581,
 0.2498554709171863,
 0.24973286944958462,
 0.24971389783908882,
 0.24875897794891821,
 0.24871082456790103,
 0.24863908179235605,
 0.24817642360087455,
 0.24737212087729088,
 0.24686486425180404,
 0.24604831092902305,
 0.24521958458795587,
 0.24432655094563535,
 0.24423281009190745,
 0.24414746807980817,
 0.24373980821887795,
 0.24327574517249914,
 0.24318507417032578,
 0.24204346887041026,
 0.24202614977714074,
 0.24166384858479262,
 0.24164718523228418,
 0.2406006042359491,
 0.24051402455768636,
 0.24041817729392795,
 0.23984303223453537,
 0.23974963412184813,
 0.23961344647164468,
 0.23941411798483253,
 0.23747519914081083,
 0.23714877314526023,
 0.23694591280124674,
 0.23655827807955962,
 0.23647914271130188,
 0.23635398923231105,
 0.23579042368572653,
 0.23549326065024315,
 0.23499751172001282,
 0.23492096759877296,
 0.23488183865289003,
 0.23438656232717306,
 0.23381842807350736,
 0.23380141146936428,
 0.23374280144240342,
 0.2336834795529634,
 0.23273764507277536,
 0.23271469983198426,
 0.23237305378849205,
 0.23220361471692738,
 0.23114395965990348,
 0.23089459881518187,
 0.23060755281984938,
 0.23026337133178065,
 0.23006425651334245,
 0.22982130102780646,
 0.22959440682232032,
 0.22944202366191116,
 0.22859785494761825,
 0.22791152794982297,
 0.22768233862821877,
 0.22700119843709124,
 0.226935026389349,
 0.22677660964688853,
 0.2267713964946441,
 0.22580708117825343,
 0.22561971452732646,
 0.22558533392486776,
 0.22531304332219518,
 0.22501834173616048,
 0.22491435558002382,
 0.22445636789686146,
 0.2240899847308698,
 0.22395640356655094,
 0.223935897578533,
 0.22384648675564586,
 0.2238422724630168,
 0.22383505416089466,
 0.2235495310533952,
 0.22241196174835168,
 0.22192161321524356,
 0.22169049148398143,
 0.22123828662062736,
 0.22091812295709728,
 0.22074884492078867,
 0.220741420694583,
 0.22071067691121002,
 0.2206360902575003,
 0.22052095680268397,
 0.22041707018086953,
 0.22039369949726992,
 0.22003528268957778,
 0.2198486186074587,
 0.21945332561116987,
 0.21932649000174873,
 0.21920316311416896,
 0.21901930105874776,
 0.21853017672604166,
 0.2180213926397472,
 0.21789653639835654,
 0.21739027212221265,
 0.21696149067030532,
 0.21680112208270447,
 0.2167282293079945,
 0.2167167173506491,
 0.21663673817684753,
 0.2165509938802447,
 0.21647489294689617,
 0.21637123366412528,
 0.2163282971601445,
 0.21622706275285428,
 0.21601993425944235,
 0.21598804110938455,
 0.21588066584723967,
 0.21582211947820862,
 0.21580403094408065,
 0.21522325281179994,
 0.21499434712075272,
 0.2149176638961392,
 0.2148516003218502,
 0.21468715056976284,
 0.21442318002992422,
 0.21403938544413317,
 0.21400986695349605,
 0.21393945162195818,
 0.2139047011720326,
 0.21322148305655975,
 0.213175713837617,
 0.21276653093258796,
 0.21272628542266864,
 0.21213405829252102,
 0.21209867463655308,
 0.21207239105606582,
 0.2119438501767729,
 0.2116519947956404,
 0.21149877070466352,
 0.21108183721623583,
 0.21077345874646064,
 0.21049508315263796,
 0.21049508315263796,
 0.2098417405990777,
 0.20969005231994173,
 0.20956035698725312,
 0.2093662569312373,
 0.20922991809111724,
 0.2091032224926309,
 0.20869485847361238,
 0.20856747800608497,
 0.20842424616084182,
 0.20832895517367206,
 0.20828700078743456,
 0.20782733168786155,
 0.20753095751497025,
 0.20738265443473772,
 0.20720706837230432,
 0.20684933452724288,
 0.2068044159031468,
 0.2066604234109807,
 0.20607266349166817,
 0.2060678539949328,
 0.2058630048138825,
 0.20486778569227795,
 0.20463581862832309,
 0.2045973715515081,
 0.2039707234807456,
 0.20366953608303587,
 0.20342831234787168,
 0.20335072481100028,
 0.20330683108870345,
 0.2032719097616019,
 0.20311913145130756,
 0.20304599673868204,
 0.20267169516104977,
 0.20244381063640848,
 0.2024126970723866,
 0.20213501713879792,
 0.20203598022334457,
 0.2019413799912681,
 0.20190893215936379,
 0.20185618516268444,
 0.20124775581462606,
 0.20115405420867194,
 0.2010752935695551,
 0.20035955663495478,
 0.19997679388927794,
 0.19966361948912537,
 0.1995845216391729,
 0.19955464011859958,
 0.19914997721272634,
 0.19887305240441414,
 0.19871464640700015,
 0.19838540000511698,
 0.19833955552354154,
 0.1982642381199513,
 0.1980069036803462,
 0.19775938007583838,
 0.1974621207628099,
 0.19746180999164534,
 0.19733774217169645,
 0.19729034998423417,
 0.19728393791576668,
 0.19719831512190564,
 0.19717691187175354,
 0.19711062898218573,
 0.19700032086702007,
 0.1968238263834237,
 0.19674793689758396,
 0.19669674742081747,
 0.19618042050938023,
 0.19617238971737727,
 0.19616946259084184,
 0.19599803109991557,
 0.19590169884199973,
 0.19587618651404212,
 0.19575173227876777,
 0.19569928974256984,
 0.1955209493758956,
 0.19550146499272283,
 0.1952749228091266,
 0.19527302778892858,
 0.19522516111196764,
 0.19517610905860486,
 0.19491900776417603,
 0.19423875700679966,
 0.19377698711812819,
 0.19370211505621807,
 0.19339470235549733,
 0.19330626038296467,
 0.19324264548030148,
 0.1932375874309235,
 0.193159872718614,
 0.19299903923370632,
 0.19266391216746173,
 0.19241723016616363,
 0.19241048437721092,
 0.19236673403358706,
 0.1921342685832149,
 0.19210828910636044,
 0.1919493881533867,
 0.1916037767978068,
 0.19140337805264077,
 0.19136192352422002,
 0.19129987738014423,
 0.19114881855318513,
 0.19111713452360912,
 0.19053508750003853,
 0.19036560819750845,
 0.19028513113900442,
 0.1899178287997437,
 0.18972403019339457,
 0.18970862441100025,
 0.18909956517853535,
 0.18890662106217584,
 0.18862904684261755,
 0.1884529604692956,
 0.18842770889186816,
 0.18837448167835782,
 0.1881615599554441,
 0.18803195455778562,
 0.1879612853042871,
 0.18788566071916335,
 0.18786813914843262,
 0.18747093331745143,
 0.18746820864027372,
 0.1872649219108036,
 0.18700863332991458,
 0.1869961241804552,
 0.1869718723093895,
 0.18663381477895186,
 0.1865172058401135,
 0.18624687203067372,
 0.18617551316617176,
 0.18575756872369678,
 0.18572965290474566,
 0.1853656533915051,
 0.18506577135543825,
 0.18504672287470922,
 0.18470208166064095,
 0.18400442032589157,
 0.18389086050024028,
 0.18381480080032359,
 0.18375084745037853,
 0.18374261016717774,
 0.18368353299924395,
 0.18352342139372455,
 0.18352260867127226,
 0.18330074214018197,
 0.18305672083275953,
 0.18299453521472148,
 0.1829085704842127,
 0.1821970895915229,
 0.18195221268275866,
 0.18176033883000883,
 0.18158739405069874,
 0.18136631833792785,
 0.18129595476113336,
 0.18105142742259775,
 0.1809279417135753,
 0.180890994999371,
 0.18060125419940665,
 0.18057525489978082,
 0.18053107799122226,
 0.1802699598363021,
 0.18022088538264525,
 0.18021941459960275,
 0.18011203743648344,
 0.17976205740529247,
 0.17955539280092597,
 0.1795060252711524,
 0.17942105725341215,
 0.1792860740067839,
 0.17898605095965495,
 0.1789768883420197,
 0.17890196032109948,
 0.1788265615505687,
 0.1787965413752595,
 0.17869094087819082,
 0.17858934676023042,
 0.17845359490269322,
 0.17819522298774826,
 0.17806216689801513,
 0.17801860182776463,
 0.17796563183949407,
 0.17790913196025684,
 0.17761047688508605,
 0.1776102590692077,
 0.17748172557591657,
 0.17716770590993222,
 0.17713261946094427,
 0.1769629590008035,
 0.17686532950581574,
 0.17671338683471552,
 0.17669440054106125,
 0.17650610413006493,
 0.1764905542182034,
 0.17643391739263373,
 0.17641540349922663,
 0.17635887683020507,
 0.1763526831799059,
 0.17630513630717204,
 0.17626370647259915,
 0.17623759437260358,
 0.17596255806144445,
 0.17565045925557127,
 0.17551546081029287,
 0.17539129794527752,
 0.175301963974081,
 0.17521322001352366,
 0.1751293596050263,
 0.17507905751614075,
 0.1747706901996548,
 0.17475306045607528,
 0.17459411515701825,
 0.17458998074216414,
 0.17457693852143122,
 0.17441139208931267,
 0.17440696317107712,
 0.1743547088618521,
 0.17428477979389354,
 0.1742019161478744,
 0.17389747327070007,
 0.17384779269366324,
 0.17383247333817642,
 0.1738045364386898,
 0.17353318535679627,
 0.17352655557518498,
 0.17302118532642255,
 0.17288278650470063,
 0.17270074079125478,
 0.17242596819879338,
 0.17228492665158238,
 0.17209657216468105,
 0.17201187493784975,
 0.17175338183139,
 0.17166757093370424,
 0.17162500023853794,
 0.1710909858696751,
 0.1709813328821846,
 0.17093033686400003,
 0.17088169868515451,
 0.17070798627395242,
 0.1707011306978092,
 0.1706748729021157,
 0.17062528779071343,
 0.17004087121176004,
 0.16984642441443626,
 0.16981691488211614,
 0.16976808808266888,
 0.1696477977445595,
 0.1693698041283766,
 0.16933787535776645,
 0.16933631330092408,
 0.1688151482200209,
 0.16848954715087047,
 0.16832688162480597,
 0.16832271798125156,
 0.1679803221038099,
 0.16793715827959058,
 0.16787654501952606,
 0.1678253142671849,
 0.1677798453840516,
 0.16773248271091556,
 0.16767296321678862,
 0.16760659362795727,
 0.16749191768412916,
 0.1674118172468303,
 0.16723735663873693,
 0.16662200986113154,
 0.16645264595829984,
 0.1664332449356287,
 0.16627551653251207,
 0.16605695923969296,
 0.16605341315470293,
 0.16599106975145134,
 0.1659764309298785,
 0.16587432890230522,
 0.16586656324651716,
 0.1656949585421971,
 0.16556563881757289,
 0.16546440475607335,
 0.16536887344750267,
 0.16536329706328928,
 0.1651994834970867,
 0.16516876571313463,
 0.16456820757829382,
 0.16452110095943054,
 0.16451312903157894,
 0.16446306115453563,
 0.1644042952825314,
 0.16431249514524432,
 0.16415285596024792,
 0.16384364350048303,
 0.1638252346110638,
 0.16375564999597864,
 0.16372681948507353,
 0.16337712501783844,
 0.16322946835794008,
 0.16256031584374306,
 0.16229095664492219,
 0.16223509984197565,
 0.16222938092215175,
 0.1619138482403557,
 0.16175515520966227,
 0.1615757309499783,
 0.16136840046609013,
 0.1613382824040703,
 0.16128364553669622,
 0.16119887646201833,
 0.16103011127013198,
 0.1610274559518051,
 0.16092671863263483,
 0.16086399804648718,
 0.16077281121718315,
 0.16053675238794743,
 0.16053022866991987,
 0.16048133038647297,
 0.16006622416459967,
 0.15996620891419194,
 0.15995133759168126,
 0.15986782170696473,
 0.15986348522817417,
 0.15977617363401786,
 0.15977175328983517,
 0.15974181649617256,
 0.1595431729489157,
 0.1595380920044315,
 0.1595373634532246,
 0.15939879616806701,
 0.15939312062966962,
 0.15922882417116924,
 0.15904986624267378,
 0.15904508488343158,
 0.15901901412633906,
 0.15899897592354045,
 0.15894510528024297,
 0.15894410384902327,
 0.15882896436420682,
 0.1586918858407881,
 0.15853850491989477,
 0.15842998711721967,
 0.158421243750889,
 0.1583912111975388,
 0.15835491766377258,
 0.15819197777637947,
 0.15819188672172635,
 0.15809654950441948,
 0.1580935827700426,
 0.15803700404937587,
 0.1579683644138727,
 0.15796748709050168,
 0.1579164609989186,
 0.1578438495927608,
 0.15775987568195363,
 0.15771550297381756,
 0.15771097178260532,
 0.15770192866694804,
 0.15768855284544858,
 0.1576053446244662,
 0.1575692855839074,
 0.15738180694240944,
 0.157195117071869,
 0.15718573852799475,
 0.15710415254477283,
 0.15676318026717467,
 0.1567219324075984,
 0.15667069508163284,
 0.1566219410375197,
 0.15657596712099317,
 0.15656929063461308,
 0.15656329507955624,
 0.15652107750471683,
 0.15642723602933806,
 0.15641667928288114,
 0.15626656608132897,
 0.1560921731920378,
 0.15597867012560157,
 0.15592469828183653,
 0.1558833574750968,
 0.1556565643957979,
 0.15560723065680956,
 0.1555603741575795,
 0.1555601129019462,
 0.15553231774085385,
 0.1554955843167344,
 0.1554856331755692,
 0.15527596909939914,
 0.1552044726204832,
 0.15518082338008038,
 0.15517037388860008,
 0.15515647915057254,
 0.1550923376574169,
 0.15500974391489578,
 0.1547845742123621,
 0.15466030408308898,
 0.15462791189199698,
 0.15459306928247854,
 0.1545563457897131,
 0.15432822028364235,
 0.1542928798868666,
 0.15422144854541833,
 0.15419711422569538,
 0.15417750079430229,
 0.1541718448735376,
 0.15416390939888996,
 0.15414170196773444,
 0.15402974417861826,
 0.15390899474466896,
 0.15374948441811112,
 0.1536499290880328,
 0.15356786217888566,
 0.15355169261580265,
 0.15353376849115222,
 0.15344597143054103,
 0.15306001347642367,
 0.1528582604284014,
 0.1528517668619453,
 0.1528273328053612,
 0.15274868851012752,
 0.15262106597409605,
 0.15257182813077522,
 0.15251847625170553,
 0.15239911596555566,
 0.15229238528927705,
 0.1522485151413181,
 0.1522085199756401,
 0.15208753303110745,
 0.15202431962678073,
 0.15193425605595093,
 0.15183629486217826,
 0.15162994309564454,
 0.15149333736102133,
 0.15145480894076652,
 0.1514379304636522,
 0.15140646771958144,
 0.151290575039085,
 0.15122423127273735,
 0.15114741568334505,
 0.15114164887826478,
 0.15108154797519482,
 0.1510340974005328,
 0.1510269828757964,
 0.15100464683515694,
 0.1509693161596235,
 0.15089629905514637,
 0.1508392547959094,
 0.15075388815052804,
 0.15069620689418245,
 0.15061341022536762,
 0.1505722645206312,
 0.1505523488590441,
 0.1504982255907823,
 0.15046240994167986,
 0.1504317336773028,
 0.15040581041827522,
 0.15033888531186723,
 0.15033628865298032,
 0.1502436414258342,
 0.15021019372876537,
 0.1501302531880385,
 0.15012764956719749,
 0.15006216033513498,
 0.15005518429126785,
 0.1499220266351645,
 0.1498532947176099,
 0.1498446237892309,
 0.14966040721396062,
 0.14958617349266803,
 0.14948281289368293,
 0.14939221213726434,
 0.14933706778030575,
 0.1490549666669956,
 0.14904061153895293,
 0.14903961634695795,
 0.14878525749861388,
 0.14863339068942696,
 0.14857978164138538,
 0.14854375449231746,
 0.14845803646669326,
 0.14843439909058853,
 0.1483513360388528,
 0.14827014781168588,
 0.1482636287378722,
 0.14825475766327617,
 0.1482543696649033,
 0.14824397466357428,
 0.1482435130092609,
 0.1481966655353679,
 0.148095495865989,
 0.14802805990898982,
 0.14799961316670246,
 0.14792719404341587,
 0.14791387301635345,
 0.14784196179074977,
 0.1478073405504755,
 0.14770059877243202,
 0.14768210435695503,
 0.14765761539953523,
 0.14758253502670124,
 0.1475286061161063,
 0.14745527666670738,
 0.14744531663308122,
 0.14739182720236255,
 0.1473597805588162,
 0.14732243000714124,
 0.14728155973299412,
 0.14724483627870766,
 0.14719190738680457,
 0.14711383405236933,
 0.147077342181518,
 0.14704633565382833,
 0.1469731315575802,
 0.14689777715461066,
 0.14678258864026084,
 0.14677407240021256,
 0.14671716504476273,
 0.14664156565204334,
 0.14661210786452444,
 0.1465939871167176,
 0.1464301957827999,
 0.14631402066078988,
 0.14626488054913786,
 0.14622907202144145,
 0.14602313881656076,
 0.14598966278354344,
 0.14594452955044887,
 0.1459177472613691,
 0.14582774707724216,
 0.14578146921951715,
 0.14567805151626964,
 0.1456463083895028,
 0.14562287383342917,
 0.14559812160079094,
 0.14558271464251,
 0.14557935182469267,
 0.14556761067022722,
 0.1455369493259411,
 0.1454570861040843,
 0.14536969082642479,
 0.14532920622388668,
 0.1452366488324308,
 0.14519206132956922,
 0.14518644271756034,
 0.1451275945124272,
 0.14505893035627213,
 0.1450458773841341,
 0.14502946115104492,
 0.1450177215040877,
 0.14499721487402512,
 0.14499602829238303,
 0.14499189277328203,
 0.1449774570024214,
 0.14496991752181482,
 0.1449406210925161,
 0.14492908122232293,
 0.14485089281624655,
 0.14482320261165027,
 0.14478456573448287,
 0.14469883925202642,
 0.14469852085783974,
 0.1446958080539341,
 0.14466323905079165,
 0.14465152159040995,
 0.14462874765137998,
 0.14462591042519266,
 0.14459548452421947,
 0.14451113972439858,
 0.144493574795656,
 0.14444082683510465,
 0.14440023114980052,
 0.14439520947296663,
 0.14430634004752763,
 0.14427200373317398,
 0.14420439249088565,
 0.1441808694389604,